name: Daily metadata refresh
on:
  schedule:
    - cron:  '5 0 * * *'   # 00:05 UTC every day
  workflow_dispatch:

jobs:
  build:
    name: Update icon metadata
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: Clone lucide-icons repo
        run: |
          git clone --depth=0 https://github.com/lucide-icons/lucide.git
      - name: List lucide/icons contents
        run: |
          ls -R lucide/icons
      - name: Use Node.js 23 for lucide
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install and run migrateIconsToCategories
        run: |
          cd lucide
          npm install --omit=dev --ignore-scripts
          node scripts/migrateIconsToCategories.mjs
      - name: Copy categories.json to project
        run: |
          mkdir -p ./src/data
          cp lucide/categories.json ./src/data/categories.json
      - run: node src/update.js

      # Commit only if files changed
      - name: Push changes if needed
        id: push_changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: daily icon metadata refresh'
          branch: gh-pages
          create_branch: true
          push_options: --force
      - name: Purge jsDelivr for all dist assets
        if: steps.push_changes.outputs.changes_detected == 'true'
        run: |
          curl -sS "https://purge.jsdelivr.net/gh/${{ github.repository }}@gh-pages/dist"
