name: Daily metadata refresh
on:
  schedule:
    - cron:  '5 0 * * *'   # 00:05 UTC every day
  workflow_dispatch:

jobs:
  build:
    name: Update icon metadata
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: node src/update.js

      # Commit only if files changed
      - name: Push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: daily icon metadata refresh'
          branch: gh-pages
          create_branch: true
          push_options: --force
